- server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
- server/src/main/java/com/gallendar/gradle/server/members/domain/Members.java
- server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepository.java
- server/src/main/java/com/gallendar/gradle/server/members/service/MemberService.java
> 🔧 add : Members Setting

- client/components/topBtn.tsx
- client/tailwind.config.js
- Top 버튼 퍼블리싱 완료
- Top 버튼 기능 구현 완료~
> ✨ Feature/ eunbi/ Top 버튼 구현 #62

- server/build.gradle
- server/src/main/java/com/gallendar/gradle/server/global/config/SecurityConfig.java
- server/src/main/java/com/gallendar/gradle/server/global/config/SwaggerConfig.java
- server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
- server/src/main/java/com/gallendar/gradle/server/members/dto/LoginResponse.java
- server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
- server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
1. swagger 추가
`implementation group: 'io.springfox', name: 'springfox-boot-starter', version: '3.0.0'`
- 3.0.0 버전에서는 swagger 접속 주소가 변경되었습니다.
- http://localhost:8080/swagger-ui/index.html
> 📈 add : swagger#142

- server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
- server/src/main/java/com/gallendar/gradle/server/category/domain/CategoryRepository.java
> 🎨 add : category#148

- server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
- server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
1. 코드에 오류가 있던 부분을 수정하였습니다.
2. Api에 대한 설명을 추가하였습니다.
> 🐛  fixed : member search 코드에 오류가 있는 부분을 수정#151

- server/src/main/java/com/gallendar/gradle/server/members/service/CreateMemberService.java
- server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
> ♻️ refactor : 순환 참조 오류 해결

- client/components/scrollImg.tsx
> ✨  Feature/ yw/ 랜딩페이지 하단 문구 스크롤에 따른 변화 구현 #60

- client/components/ConfirmBtn.tsx
- client/components/WelcomeModal.tsx
- client/package-lock.json
- client/package.json
- client/tailwind.config.js
- React Hook Form 라이브러리 설치후 변경된 package.json, package-lock.json 업로드
- tailwind.config파일 내 색상코드 추가 및 병합 충돌 해결했습니다
- 담당했던 환영 모달 + 확인 버튼 구현했습니다
> ✨ Feature/ eunbi/ React hook form 설치 및 색상코드 추가, 환영모달 구현#83

- server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
- server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
- server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
- server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
- server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
- server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
- server/src/main/java/com/gallendar/gradle/server/tags/dto/NotificationResponse.java
- server/src/test/java/com/gallendar/gradle/server/board/BoardSearchTest.java
1. 게시글 조회 구현
* year, month, day, category 조건에 맞는 응답 결과를 다이나믹쿼리로 구현
> Feature/dg/board search#201

- client/components/CalendarContainer.tsx
- client/components/CalendarNav.tsx
- client/components/CalendarPageLayout.tsx
- client/pages/calendar.tsx
- client/pages/main.tsx
- client/tailwind.config.js
- calendar 레이아웃 초기작업
- calendar navigation bar 초기작업
- tailwind css 색상 추가
> ✨ Feature/ eunbi/ calendar 컴포넌트 관련 초기작업

- server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
- server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchByIdResponse.java
- server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
- server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
- server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
- server/src/test/java/com/gallendar/gradle/server/board/BoardSearchTest.java
1. board search by id
* 자신이 작성한 게시글에 접근 할 수 있다.
> Feature/dg/board search by id#238

- server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustom.java
- server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustomImpl.java
- server/src/main/java/com/gallendar/gradle/server/tags/controller/TagConditionController.java
- server/src/main/java/com/gallendar/gradle/server/tags/dto/CountBoardResponse.java
- server/src/main/java/com/gallendar/gradle/server/tags/service/TagService.java
- server/src/test/java/com/gallendar/gradle/server/board/TagConditionTest.java
1. 태그 당한 유저의 해당 날짜의 게시글 개수 반환
* 하루에 자신의 작성한 게시글 1개 + 공유를 수락하였을 때의 게시글 1개 = 총 2개의 게시글을 하루에 가질 수 있다.
> Feature/dg/tag member condition#241

- client/components/AddPhotoContainer.tsx
- client/package-lock.json
- client/package.json
- AddPhotoContainer 컴포넌트 파일 내 이미지 업로드 기능 구현
- 위치 기능구현을 위한 exif-ts 설치
> ✨ Feature /  eunbi /  이미지 업로드 구현, exif-ts 라이브러리 설치

- client/components/AddPhotoContainer.tsx
- client/components/CalendarContainer.tsx
- client/components/CreateModalLayout.tsx
-AddPhotoContainer, CreateModalLayout 내 이미지 업로드 관련 코드 수정
- CalendarContainer height 수정
> ✨ Feature/ eunbi/ 이미지 업로드 관련 코드수정

- client/components/CalendarBody.tsx
- client/components/CalendarPageLayout.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/recoil/calendarAtom.tsx
💡구현사항
✔️+버튼 클릭 시 해당 날짜코드 받기 구현
> ✨ Feature/sunghun/+버튼 클릭 시 해당 날짜코드 받아오기 완료

- server/.gitignore
- server/src/main/java/com/gallendar/gradle/server/deploy/DeployTest.java
- server/src/main/resources/application.yml
> Feature/jungsoyi/cicd #277

- client/components/CalendarPageLayout.tsx
- client/components/LoginForm.tsx
- client/components/MyBoard.tsx
- client/components/SharedBoard.tsx
- client/recoil/authAtom.ts
- 캘린더 화면 내 보일 게시글의 타이틀(컨테이너) 레이아웃 구현했습니다. (MyBoard, SharedBoard) 
- 로그인 시 userId 받아와 리코일 전역 상태로 저장시켰습니다. (userIdState)
> ✨ Feature / eunbi/ 게시글타이틀 컨테이너 구현

- client/apis/board/getBoards.tsx
- client/apis/board/getCategory.tsx
- client/client/client.tsx
- client/components/CalendarBody.tsx
- client/components/CalendarContainer.tsx
- client/components/CalendarPageLayout.tsx
- client/components/CertifyPageLayout.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/components/MyBoard.tsx
- client/components/SharedBoard.tsx
- client/components/Sidebar.tsx
- client/hooks/calendar/useGetBoards.tsx
- client/hooks/calendar/useGetCategory.tsx
- client/pages/calendar.tsx
- client/pages/signup.tsx
- calendar 페이지 내 게시글 전체 조회기능 구현
- calendar 특정 날짜에 게시글 존재 시 addBtn 비활성화 
- category get요청 로직
> ✨ Feature/ eunbi/ 캘린더 특정 날짜에 게시글 조회기능구현#276

- client/apis/board/postBoardData.tsx
- client/client/formClient.tsx
- client/components/AddPhotoContainer.tsx
- client/components/CalendarPageLayout.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/hooks/calendar/usePostBoard.tsx
- client/recoil/calendarAtom.tsx
💡작업사항
✔️게시글 작성 후 저장버튼 누를시 서버로 요청 및 DB저장 구현 완료
> ✨Feature/sunghun/게시글작성모달 api연결 완료

- server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
- server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCountResponse.java
- server/src/main/java/com/gallendar/gradle/server/board/service/BoardCountService.java
- server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustom.java
- server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustomImpl.java
- server/src/test/java/com/gallendar/gradle/server/board/CountBoardTest.java
- server/src/test/java/com/gallendar/gradle/server/board/QuitMemberTest.java
1. 게시글 작성 여부 반환
* 경우의 수      전체 게시글  태그된 게시글       전체게시글-태그된 게시글
* 0 0            0            0                   0 가능
* 0 1            1            1                   0 가능
* 1 0            1            0                   1 불가능
* 1 1            2            1                   1 불가능
* 게시글 작성자가 다른 요일로 선택하였을 경우를 고려
> ✨ feat : 게시글 작성 여부 반환#286

- server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
- server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
> 🎨  fixed : boardSearchResponse 응답 수정

- client/components/CalendarBody.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/components/MyBoard.tsx
- client/components/Sidebar.tsx
- client/components/noticeLayout.tsx
- client/hooks/calendar/usePostBoard.tsx
- 병합 후 충돌로 인해 틀어진 코드 수정 
- 알림 모달 레이아웃 작업 진행중
> ✨ Feature/ eunbi/ 알림 모달 레이아웃 작업

- client/apis/notice/getShareNotice.tsx
- client/components/CalendarBody.tsx
- client/components/CalendarContainer.tsx
- client/components/DayBlock.tsx
- client/components/ShareNotice.tsx
- client/components/noticeLayout.tsx
- client/hooks/notice/useGetShareNotice.tsx
- client/pages/mypage.tsx
- client/styles/globals.css
- 공유알림 레이아웃 구현 (global css 에 말풍선 스타일 작성) 
- 공유알림 기능 로직 구현
> ✨ Feature / eunbi/  알람 레이아웃 및 기능로직구현

- server/.gitignore
- server/build.gradle
- server/scripts/deploy.sh
jenkins에서 빌드할 때, QueryDsl 에러가 발생. 빌드할때마다 초기화 해주는 항목 추가
> :green_heart: build.gradle 수정

- server/src/main/resources/logback.xml
`java.nio.charset.UnmappableCharacterException: Input length = 1`
1. 젠킨스 배포시 한글 주석 처리가 제대로 되지 않아 생기는 오류
> 📝delete : 한글 주석 제거#304

- client/apis/notice/getAcceptNotification.tsx
- client/apis/notice/getDenyNotification.tsx
- client/components/CalendarBody.tsx
- client/components/CalendarNav.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/components/MyBoard.tsx
- client/components/ShareNotice.tsx
- client/components/ShareNoticeContainer.tsx
- client/components/SharedBoard.tsx
- client/components/ShippingNotice.tsx
- client/components/ShippingNoticeContainer.tsx
- client/hooks/notice/useGetAcceptNotice.tsx
- client/hooks/notice/useGetDenyNotice.tsx
- client/pages/mypage.tsx
- client/styles/globals.css
- 공유알림 모달 기능 구현 (ShareNotice)
- 배송알림 모달 레이아웃 구현 
- 알림모달 반응형 mediaQuery 조건 수정 (global css) 
- 공유 받은 게시글과 내 게시글 한 날짜에 보여지도록 캘린더 로직 수정 (calendarBody, dayBlock)
> ✨ Feature / eunbi / 알림 모달 기능 구현 및 캘린더 로직 수정

- client/components/CalendarBody.tsx
- client/components/CalendarNav.tsx
- client/components/DayBlock.tsx
- client/components/ShareNoticeContainer.tsx
- client/components/Sidebar.tsx
- client/components/SidebarCategory.tsx
- client/components/TopBtn.tsx
- client/hooks/notice/useGetShareNotice.tsx
- client/pages/index.tsx
- client/recoil/calendarAtom.tsx
- 공유 알림 모달(ShareNotice)에서 선택한 버튼에 따라 캘린더에 적용되도록 구현완료
- 선택한 카테고리에 선택된 표시 입히는 기능 구현 완료
> ✨ Feature / eunbi /  알림 적용 기능 구현 및 카테고리 선택 기능 구현

- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
💡작업사항
✔️새로고침 시 모달창 활성화 현상 버그 수정
✔️ReadModalLayout 무한요청버그 수정
> 🐛 Fixed/sunghun/ReadmodalLayout 무한요청버그 수정

- client/components/CreateModalLayout.tsx
> 🐛 Fixed/sunghun/게시글 작성모달 버튼 버그 수정

- client/components/DayBlock.tsx
- client/components/TopBtn.tsx
- client/pages/index.tsx
> 🐛  fixed / eunbi /  현재 날짜 스타일 버그 수정

- server/src/main/java/com/gallendar/gradle/server/members/controller/MemberInfoController.java
- server/src/main/java/com/gallendar/gradle/server/members/dto/MemberTagStatusRequest.java
- server/src/main/java/com/gallendar/gradle/server/members/dto/MemberTagStatusResponse.java
- server/src/main/java/com/gallendar/gradle/server/members/service/MemberInfoService.java
- server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepositoryCustom.java
- server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepositoryCustomImpl.java
- server/src/test/java/com/gallendar/gradle/server/tags/GetSharedStatusTest.java
> Feature/dg/tag status log#338

- client/components/CheckMyLog.tsx
- client/components/MyPageSidebarToggle.tsx
- client/components/MyPageUserBox.tsx
- client/components/MySidebarCategory.tsx
- client/components/SelectBar.tsx
- client/pages/mypage.tsx
구현사항
- 마이페이지 CSS 구현 완료
- 회원 탈퇴 구현
- 카테고리 선택바 버그 수정
> ✨ Feature / yw/ 마이페이지 CSS구현 및 회원탈퇴기능 구현/ #94

- server/src/main/java/com/gallendar/gradle/server/global/config/SecurityConfig.java
1.  WebSecurityConfigurerAdapter deprecated 대체
> 🐛 fixed : cors error#341

- client/apis/mypage/getSharedLog.tsx
- client/components/CheckMyLog.tsx
- client/components/LogContainer.tsx
- client/components/LogDetail.tsx
- client/components/MyPageUserBox.tsx
- client/pages/mypage.tsx
- 전반적인 Mypage 레이아웃 및 로직 수정하였습니다.
> ✨ Feature/ eunbi/ mypage 레이아웃 및 로직 수정

- client/package-lock.json
- client/package.json
- 마이페이지 내 페이지네이션 사용을 위해 react-js-pagination 라이브러리 설치하였습니다.
> ✨ Feature/ eunbi / react-js-pagination 라이브러리 설치

- server/src/main/java/com/gallendar/gradle/server/members/controller/MemberInfoController.java
- server/src/main/java/com/gallendar/gradle/server/members/service/MemberInfoService.java
> 🎨 fixed : response page#348

- client/apis/mypage/getSharedLog.tsx
- client/components/CheckMyLog.tsx
- client/components/commerceContainer.tsx
- client/components/commerceSidebar.tsx
- client/package-lock.json
- client/package.json
- client/pages/commerce.tsx
- client/styles/globals.css
- commerce 임시 페이지 서비스 준비중 레이아웃 구현했습니다.
> ✨ Feature / eunbi / 커머스 페이지 초기 작업

- client/components/CreateModalLayout.tsx
- 카테고리 엔터 혹은 선택 시 다음 칸으로 입력 할 수 있도록 수정
> ✨ Feature/ yw/ 카테고리 버그 수정

- client/components/CalendarNav.tsx
- client/components/CalendarPageLayout.tsx
- client/components/DayBlock.tsx
- client/components/ShareNotice.tsx
- client/components/ShareNoticeContainer.tsx
- client/components/ShippingNotice.tsx
- client/components/ShippingNoticeContainer.tsx
- client/recoil/calendarAtom.tsx
- 공유알림 렌더 관련 수정 중 
- 알림 모달 서비스 준비중 띄워두었습니다.
> 🐛 fixed / eunbi / 공유알림  기능 수정 및 알림 레이아웃 수정 

- client/components/SelectBar.tsx
> 🐛 Fixed/ yw/ 카테고리 선택바 버그 수정

- client/components/AddPhotoContainer.tsx
- client/components/CalendarNav.tsx
- client/components/CheckMyLog.tsx
- client/components/CreateModalLayout.tsx
- client/components/DayBlock.tsx
- client/components/LoginForm.tsx
- client/components/ShareNotice.tsx
- client/components/ShareNoticeContainer.tsx
- client/components/SharedBoard.tsx
- client/hooks/notice/useGetShareNotice.tsx
- client/pages/index.tsx
- client/recoil/calendarAtom.tsx
- shareNotice 마운트 시 알림이 있는 경우 확인시켜주는 스타일 적용 및 바로 적용 및 조회되도록 수정
> 🐛 Fixed/ eunbi / 공유알림 바로 적용되지 않는 버그 해결

- server/src/main/java/com/gallendar/gradle/server/members/service/MemberInfoService.java
> 🐛  fixed : tag log pageable

- client/apis/auth/checkAuthNum.tsx
- client/apis/auth/postAuthNum.tsx
- client/apis/user/checkEmail.tsx
- client/apis/user/checkUserId.tsx
- client/apis/user/postSignUp.tsx
- client/components/signupComp/SignUpCode.tsx
- client/components/signupComp/SignUpEmail.tsx
- client/components/signupComp/SignUpId.tsx
- client/components/signupComp/SignUpIllust.tsx
- client/components/signupComp/SignUpPw.tsx
- client/hooks/user/useCheckAuthNum.tsx
- client/hooks/user/useCheckEmail.tsx
- client/hooks/user/useCheckUserId.tsx
- client/hooks/user/usePostSignUpData.tsx
- client/hooks/user/useRequestAuthNum.tsx
- client/package-lock.json
- client/package.json
- client/pages/resignup.tsx
- client/recoil/refacAtom.tsx
- SignUp 코드 간결화를 위한 리팩토링
- resignup 파일 생성
> ♻️ refactor : SignUp페이지 코드 리팩토링
